OnlineShop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineShop.Models;

namespace OnlineShop.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private OnlineShopContext db = new OnlineShopContext();

        // GET: Admin
        public async Task<ActionResult> Index()
        {
            return View(await db.CarModels.ToListAsync());
        }

        // GET: Admin/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = await db.CarModels.FindAsync(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            return View(carModel);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CarModelId,NameModel,NameManufacturer,NameCategory,Description,Price")] CarModel carModel)
        {
            if (ModelState.IsValid)
            {
                db.CarModels.Add(carModel);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(carModel);
        }

   
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = await db.CarModels.FindAsync(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            return View(carModel);
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CarModelId,NameModel,NameManufacturer,NameCategory,Description,Price")] CarModel carModel, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    carModel.ImageMimeType = image.ContentType;
                    carModel.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(carModel.ImageData, 0, image.ContentLength);
                }


                db.Entry(carModel).State = EntityState.Modified;

                await db.SaveChangesAsync();
                TempData["message"] = string.Format("Изменения  \"{0}\" были сохранены", carModel.CarModelId);
                return RedirectToAction("Index");
            }
            else
            {
                return View(carModel);
            }
     
        }

        // GET: Admin/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = await db.CarModels.FindAsync(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            return View(carModel);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CarModel carModel = await db.CarModels.FindAsync(id);
            db.CarModels.Remove(carModel);
            TempData["message"] = string.Format("Модель  \"{0}\" была удалена", carModel.CarModelId);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShop/Controllers/CarModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShop.Services;
using OnlineShop.Models;
using OnlineShop.Controllers;
using OnlineShop.Infrastructure;
using OnlineShop.Interface;
using Ninject;
using PagedList.Mvc;
using PagedList;

namespace OnlineShop.Controllers
{
    public class CarModelController : Controller
    {

        private readonly IRepository<CarModel> carRepository;

        public CarModelController(IRepository<CarModel> carRepository)
        {
            this.carRepository = carRepository;
        }
        public FileContentResult GetImage(int gameId)
        {
            CarModel car = carRepository.GetAll()
                .FirstOrDefault(g => g.CarModelId == gameId);

            if (car != null)
            {
                return File(car.ImageData, car.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public ViewResult List(string category, int page = 1)
        {
            int pageSize = 3;
           
            CarListViewModel carListViewModel = new CarListViewModel
            {
                CarModels = carRepository.GetAll()
                .Where(p => category == null || p.NameCategory == category)
                .OrderBy(p => p.NameModel)
                .Skip((page-1)*pageSize)
                .Take(pageSize),              
                PageInfo = new PageInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ? carRepository.GetAll().Count() : 
                    carRepository.GetAll().Where(c => c.NameCategory == category).Count()
                    
                },
                CurrentCategory = category
            };
      
            return View(carListViewModel);
        }
       
    }
}

OnlineShop/Views/Admin/Create.cshtml
@model OnlineShop.Models.CarModel

@{
    ViewBag.Title = "Create";
}


<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Новая модель</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    <div class="panel-body">
        <div class="form-horizontal">


            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.NameModel, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameModel, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NameModel, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NameManufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameManufacturer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NameManufacturer, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NameCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameCategory, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NameCategory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
                <div class="panel-footer">
                    <input type="submit" value="Сохранить" class="btn btn-danger" />
                    @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
                    {
                        @class = "btn btn-default"
                    })
                </div>
            

            }
        </div>
 
     

OnlineShop/Views/Admin/Delete.cshtml
@model OnlineShop.Models.CarModel

@{
    ViewBag.Title = "Delete";
}



<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Удалить</h3>
    </div>


    <div class="panel-body">


        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NameModel)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameModel)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NameManufacturer)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameManufacturer)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NameCategory)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameCategory)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

        </dl>
    </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="panel-footer">
                <input type="submit" value="Удалить" class="btn btn-primary" />
                @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
                {
                    @class = "btn btn-default"
                })
            </div>
        }
  
</div>

OnlineShop/Views/Admin/Details.cshtml
@model OnlineShop.Models.CarModel

@{
    ViewBag.Title = "Details";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Детали</h3>
    </div>

    <div class="panel-body">


        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NameModel)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameModel)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NameManufacturer)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameManufacturer)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NameCategory)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameCategory)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

        </dl>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Редактировать", "Edit", new { id = Model.CarModelId }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
        {
            @class = "btn btn-default"
        })
    </div>
</div>

OnlineShop/Views/Admin/Edit.cshtml
@model OnlineShop.Models.CarModel

@{
    ViewBag.Title = "Админ панель: редактирование товара";
}




<div class="panel panel-default">
    <div class="panel-heading">
       
    </div>

    @using (Html.BeginForm("Edit", "Admin",FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="panel-body">
            @Html.HiddenFor(m => m.CarModelId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "CarModelId":
                    case "ImageData":
                    case "ImageMimeType":
                        // Ничего не делать
                        break;
                    default:
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @if (property.PropertyName == "CarModelId")
                {
                   @Html.HiddenFor(m => m.CarModelId)
                }

                @if (property.PropertyName == "Description")
                {
                    @Html.TextArea(property.PropertyName, null,
                        new { @class = "form-control", rows = 5 })
                }
                else
                {
                    @Html.TextBox(property.PropertyName, null,
                        new { @class = "form-control" })
                }
                @Html.ValidationMessage(property.PropertyName)
            </div>
                        break;
                }
            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Картинка</label>
                    <a class='btn' href='javascript:;'>
                        Выберите файл...
                        <input type="file" name="Image" size="4000"
                               style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">Нет картинки</div>
                }
                else
                {
                    <img class="img-thumbnail" width="1200" height="1200"
                         src="@Url.Action("GetImage", "CarModel", new { gameId = Model.CarModelId })" />
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-danger" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

OnlineShop/Views/Admin/Index.cshtml
@model IEnumerable<OnlineShop.Models.CarModel>

@{
    ViewBag.Title = "Админ панель: список товаров";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>List of cars</h3>
    </div>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
 
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr class="text-center text-danger">
                <th>ID</th>
                <th>Модель</th>
                <th>Производитель</th>
                <th>Категория</th>
                <th>Описание</th>
                <th>Цена</th>
                <th>Действия</th>
            </tr>
            @foreach (var item in Model)
            {
            <tr class="text-center">
                <td>@item.CarModelId</td>
                <td>@Html.ActionLink(item.NameModel, "Edit", new { id = item.CarModelId })</td>
                <td>@item.NameManufacturer</td>
                <td>@item.NameCategory</td>
                <td>@item.Description</td>
                <td>@item.Price.ToString()</td>
                <td>@Html.ActionLink("Details", "Details", new { id = item.CarModelId })   @Html.ActionLink("Delete", "Delete", new { id = item.CarModelId })</td>


            </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add Car", "Create", null,
            new { @class = "btn btn-danger" })
    </div>
</div>