OnlineShop/Controllers/CarModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShop.Services;
using OnlineShop.Models;
using OnlineShop.Controllers;
using OnlineShop.Infrastructure;
using OnlineShop.Interface;
using Ninject;
using PagedList.Mvc;
using PagedList;

namespace OnlineShop.Controllers
{
    public class CarModelController : Controller
    {

        private readonly IRepository<CarModel> carRepository;

        public CarModelController(IRepository<CarModel> carRepository)
        {
            this.carRepository = carRepository;
        }
        public FileContentResult GetImage(int gameId)
        {
            CarModel car = carRepository.GetAll()
                .FirstOrDefault(g => g.CarModelId == gameId);

            if (car != null)
            {
                return File(car.ImageData, car.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
        public ViewResult List(string category, int page = 1)
        {
            int pageSize = 3;
           
            CarListViewModel carListViewModel = new CarListViewModel
            {
                CarModels = carRepository.GetAll()
                .Where(p => category == null || p.NameCategory == category)
                .OrderBy(p => p.NameModel)
                .Skip((page-1)*pageSize)
                .Take(pageSize),              
                PageInfo = new PageInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ? carRepository.GetAll().Count() : 
                    carRepository.GetAll().Where(c => c.NameCategory == category).Count()
                    
                },
                CurrentCategory = category
            };
      
            return View(carListViewModel);
        }
       
    }
}

OnlineShop/Controllers/CartController.cs
using OnlineShop.Interface;
using OnlineShop.Models;
using OnlineShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class CartController : Controller
    {

        private readonly IRepository<CarModel> carRepository;
        private readonly IOrderProcessor orderProcessor;
        public CartController(IRepository<CarModel> carRepository , IOrderProcessor orderProcessor)
        {
            this.carRepository = carRepository;
            this.orderProcessor = orderProcessor;
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
      
        public RedirectToRouteResult AddToCart(Cart cart,int gameId, string returnUrl)
        {
            CarModel game = carRepository.GetAll()
                .FirstOrDefault(g => g.CarModelId == gameId);

            if (game != null)
            {
                cart.AddItem(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart,int gameId, string returnUrl)
        {
            CarModel game = carRepository.GetAll()
                .FirstOrDefault(g => g.CarModelId == gameId);

            if (game != null)
            {
                cart.RemoveLine(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

     
    }

}

OnlineShop/Controllers/NavigationController.cs
using OnlineShop.Interface;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class NavigationController : Controller
    {
        private readonly IRepository<CarModel> carRepository;
        public NavigationController(IRepository<CarModel> carRepository)
        {
            this.carRepository = carRepository;
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = carRepository.GetAll()
                .Select(m => m.NameCategory)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }      
    }
}

OnlineShop/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>


</head>
<body>
    @RenderBody()

</body>
</html>

OnlineShop/Views/Shared/CarSummary.cshtml
@model OnlineShop.Models.CarModel


<div class="well">

    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="159" height="150"
                 src="@Url.Action("GetImage", "CarModel",
                new { gameId = Model.CarModelId })" />
        </div>
    }
    <h4>
        <strong>@Model.NameManufacturer @Model.NameModel</strong>

        <span class="pull-right">@Model.Price.ToString("# $")</span>
    </h4>
    <p>@Model.NameCategory</p>
    @using (Html.BeginForm("AddToCart", "Cart", new { gameId = Model.CarModelId }))
    {
        <div class="pull-right">
            @Html.HiddenFor(model => model.CarModelId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success btn-danger" value="Купить этот автомобиль" />
        </div>
    }
    <p>@Model.Description</p>
</div>

OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>American Auto </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" media="screen">
    <link href="~/Content/MyStyle.css" rel="stylesheet" media="screen">


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light ">
        <a class="navbar-brand" href="@Url.Action("List", "CarModel")">
            <img src="~/Images/american-auto.png" alt="Logo" style="width:150px;">
        </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        <ul class="navbar-nav mr-auto">

            @if (User.Identity.IsAuthenticated && User.Identity.Name != "Admin")
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-danger"  id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Wellcome @User.Identity.Name

                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("Edit", "Account")">My profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Logout", "Account")">Logout</a>
                    </div>
                </li>


            }
            else if (User.Identity.Name != "Admin")
            {

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-danger" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Home <i class="glyphicon glyphicon-home"> </i>

                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("Login", "Account")">Login</a>
                        <a class="dropdown-item" href="@Url.Action("Registration", "Account")"> Sign Up</a>
                    </div>
                </li>
               
                           
            }
            else if (User.Identity.Name == "Admin")
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-danger"  id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Wellcome @User.Identity.Name

                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("Index", "Admin")">Cars</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Logout", "Account")">Logout</a>
                    </div>
                </li>
            }
        </ul>



    </nav>

    <div>
        <div id="categories" class="col-xs-2">
            @Html.Action("Menu", "Navigation")
        </div>
        <div class="col-xs-8">
            @RenderBody()


        </div>

    </div>
    <footer class="card-footer fixed-bottom text-danger">
       
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>